---
driver:
  name: vagrant
  network:
  - ["forwarded_port", {guest: 80, host: 8080, auto_correct: true}]

platforms:
- name: ubuntu-12.04
  run_list:
    - recipe[apt]
- name: ubuntu-14.04
  run_list:
    - recipe[apt]
- name: debian-7.6
  run_list:
    - recipe[apt]
- name: centos-6.5
- name: fedora-19
- name: fedora-20

suites:
- name: default
  run_list:
    - recipe[postfix-dovecot_test]
  attributes: { }
