---
driver:
  name: vagrant
  network:
  - ["forwarded_port", {guest: 80, host: 8080, auto_correct: true}]

platforms:
- name: ubuntu-12.04
  run_list:
    - recipe[apt]
- name: ubuntu-14.04
  run_list:
    - recipe[apt]
- name: debian-7.6
  run_list:
    - recipe[apt]
- name: centos-6.5
- name: fedora-19
- name: fedora-20

suites:
- name: mysql
  run_list:
    - recipe[postfix-dovecot_test]
  attributes: {}
- name: postgresql
  excludes:
  # https://github.com/hw-cookbooks/postgresql/issues/97
  # https://github.com/hw-cookbooks/postgresql/issues/108
  - ubuntu-12.04
  - ubuntu-14.04
  - debian-6.0.10
  - debian-7.6
  - debian-7-0-x64
  run_list:
  - recipe[postfix-dovecot_test]
  attributes:
    postfix-dovecot:
      database:
        type: postgresql
